<a href="https://colab.research.google.com/github/VivekMuraleedharanGit/Spam-Classifier/blob/main/spam_message_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np


In [31]:
data= pd.read_csv('/content/drive/MyDrive/Data Science /Data Science notebooks/SMSSpamCollection',sep='\t',header=None,names=['Label','SMS'])
data.head()

Label                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
data.shape

(5572, 2)

In [ ]:
data.Label.value_counts(normalize=True)

ham     0.865937
spam    0.134063
Name: Label, dtype: float64

In [ ]:
data['SMS']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: SMS, Length: 5572, dtype: object

In [32]:
data['Label']= data['Label'].map({'ham':0,'spam':1})

In [33]:
data['Label']

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Label, Length: 5572, dtype: int64

In [20]:
data.head()

Label                                                SMS
0      0  Go until jurong point crazy Available only in ...
1      0                            Ok lar Joking wif u oni
2      1  Free entry in  a wkly comp to win FA Cup final...
3      0        U dun say so early hor U c already then say
4      0  Nah I dont think he goes to usf he lives aroun...

In [34]:
import re
def cleaned(doc):
  doc = doc = re.sub(r'[^a-zA-Z\s]', '', doc, re.I|re.A)
  return doc

In [35]:
data['SMS']= data['SMS'].apply(cleaned)

In [36]:
x = data['SMS']
y = data['Label']

In [37]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Label, Length: 5572, dtype: int64

In [12]:
x.head()

0    Go until jurong point crazy Available only in ...
1                              Ok lar Joking wif u oni
2    Free entry in  a wkly comp to win FA Cup final...
3          U dun say so early hor U c already then say
4    Nah I dont think he goes to usf he lives aroun...
Name: SMS, dtype: object

In [38]:

#splitting the data set into train test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)

x_train.shape,x_test.shape,y_train.shape

((3900,), (1672,), (3900,))

In [22]:
x_train[4060]

'Moby Pub QuizWin a  High Street prize if u know who the new Duchess of Cornwall will be Txt her first name to unsub STOP   SP'

In [39]:
#cleaning the dataset and converting into tf-idf format

from sklearn.feature_extraction.text import TfidfVectorizer

tf= TfidfVectorizer(lowercase=True,ngram_range=(1,2),
                    stop_words = 'english',max_df = 0.5,min_df =2,use_idf =True)

tf_matrix_train = tf.fit_transform(x_train)
tf_matrix_train = tf_matrix_train.toarray()

vocab = tf.get_feature_names()
vocab[1:10]

['aathilove',
 'aathilove lot',
 'aathiwhere',
 'aathiwhere dear',
 'ability',
 'abiola',
 'able',
 'able come',
 'able pay']

In [48]:
tf_matrix_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
tf_matrix_test = tf.transform(x_test)

In [41]:
#import the model

from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [42]:
#training
nb.fit(tf_matrix_train,y_train)
#prediction
pred = nb.predict(tf_matrix_test)

In [43]:
pred

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
# confusion matrics

from sklearn.metrics import confusion_matrix,accuracy_score

confusion_matrix(y_test,pred)


array([[1442,    0],
       [  58,  172]])

In [46]:
x_test[(pred==0) & (y_test==1)]

147     FreeMsg Why havent you replied to my text Im R...
1064    We have new local dates in your area  Lots of ...
1777                                Call FREEPHONE    now
2680    New Tones This week include McFlyAll Ab  Sara ...
1217                 You have  new voicemail Please call 
5566    REMINDER FROM O To get  pounds free call credi...
881     Reminder You have not downloaded the content y...
4376    Ur TONEXS subscription has been renewed and yo...
3132    LookAtMe Thanks for your purchase of a video c...
2295                   You have  new message Please call 
420     Send a logo  ur lover   names joined by a hear...
5110                   You have  new message Please call 
1045    We know someone who you know that fancies you ...
3443    Save money on wedding lingerie at wwwbridalpet...
2583     FREE TAROT TEXTS Find out about your love lif...
943     How about getting in touch with folks waiting ...
5       FreeMsg Hey there darling its been  weeks now ...
3856    Free m